name: Prison Lockdown
main: io.github.matho97.lockdown.Lockdown
version: 1.0.1
commands:
  lockdown:
    description: Commands for lockdown.
    usage: Usage /lockdown
    permission: lockdown
    permission-message: You don't have access to 'Lockdown'
    aliases: [ld, lockd, ldown]
permissions:
  lockdown.execute:
   default: op
  lockdown.reload:
   default: op
  lockdown.set:
   default: op
  lockdown.timeleft:
   default: op
  lockdown.immune:
    default: op