name: Lockdown
main: io.github.matho97.lockdown.Lockdown
version: 0.1.0
commands:
  lockdown:
    description: Commands for lockdown.
    usage: Usage /lockdown help
    permission: lockdown.lockdown.execute
    permission-message: You don't have access to lockdown.lockdown.execute
permissions:
    lockdown.lockdown.immune:
      default: op